version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  backend:
    container_name: api-server
    image: node:latest
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=todo
    depends_on:
      - db

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build"

  db:
    image: mysql:5.7
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todo
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

